- name: Linux target
  hosts: all
  become: true
  tasks:
    - name: Copy the flag
      ansible.builtin.copy:
        src: ./data/flag.txt
        dest: /tmp/flag.txt
        mode: '0777'
    - name: Copy resources for salt
      ansible.builtin.copy:
        src: ./data/salt
        dest: /etc/
        mode: '0777'
    - name: Install requirements
      ansible.builtin.apt:
        pkg:
        - unzip
        - wget
        - python3-pip
        update_cache: yes
    - name: Copy vulnerable salt source
      ansible.builtin.unarchive:
        src: ./data/v3002.zip
        dest: /home/vagrant
        mode: '0777'
    - name: Run the setup
      ansible.builtin.script: ./data/setup.sh